name: Build executables

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build:
    if: github.ref == 'refs/heads/main'
    name: Build ${{ matrix.goos }}-${{ matrix.goarch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - goos: linux
            goarch: amd64
            ext: ""
          - goos: linux
            goarch: arm64
            ext: ""
          - goos: windows
            goarch: amd64
            ext: ".exe"
          - goos: darwin
            goarch: amd64
            ext: ""
          - goos: darwin
            goarch: arm64
            ext: ""
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Download dependencies
        run: go mod download

      - name: Build executable
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0
          GOTRAY_SECRET: ${{ secrets.GOTRAY_SECRET }}
          TRMM_APIKEY: ${{ secrets.TRMM_APIKEY }}
        run: |
          set -euo pipefail
          mkdir -p dist
          output="dist/gotray-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.ext }}"
          if [ -z "${GOTRAY_SECRET}" ]; then
            echo "GOTRAY_SECRET GitHub secret is required to build release artifacts" >&2
            exit 1
          fi
          if [ -z "${TRMM_APIKEY}" ]; then
            echo "TRMM_APIKEY GitHub secret is required to embed the Tactical RMM credential" >&2
            exit 1
          fi
          ldflags=$(printf '%q %q' "-X github.com/example/gotray/internal/config.CompiledSecret=${GOTRAY_SECRET}" "-X github.com/example/gotray/internal/trmm.embeddedAPIKey=${TRMM_APIKEY}")
          go build -trimpath -ldflags "${ldflags}" -o "$output" ./cmd/gotray

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gotray-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/gotray-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.ext }}
          if-no-files-found: error
